sparcs-kaist/otlplus-app

.gitignore
ios/Flutter/Debug.xcconfig
ios/Flutter/Release.xcconfig
ios/Podfile
ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcworkspace/contents.xcworkspacedata
lib/widgets/backdrop.dart

- changed ios status bar color
- ios에서 상태바 색상을 바꾸었습니다.
- change `.gitignore` for more ignoring files in `ios/`
- `ios/`에서 더 많은 파일을 무시하도록 `.gitignore`을 바꾸었습니다.
| before | after |
|:---:|:---:|
|<img width="539" alt="Screen Shot 2021-01-28 at 1 29 10 AM" src="https://user-images.githubusercontent.com/34997549/106022262-ff8d1200-6108-11eb-9314-c459687ca8e1.png">|<img width="539" alt="Screen Shot 2021-01-28 at 1 29 00 AM" src="https://user-images.githubusercontent.com/34997549/106022306-0b78d400-6109-11eb-8a87-42e9e5ee546a.png">|
Status bar color on android remains white.
안드로이드에서의 상태바는 흰색으로 남겨두었습니다.

Changed ios status bar color

---

lib/pages/course_detail_page.dart
lib/pages/review_page.dart
lib/widgets/course_search.dart
lib/widgets/lecture_search.dart

Fixed issue #24 
Fixed scrollbar not visible on review page, course history detail and course search list view
Added circular progress indicator while loading more reviews in review page

Fix #24 (scroll issue), add progress indicator on review loading

---

lib/pages/lecture_detail_page.dart
lib/pages/main_page.dart
lib/pages/timetable_page.dart
lib/providers/timetable_model.dart
lib/widgets/lecture_search.dart
lib/widgets/timetable_tabs.dart
pubspec.yaml

- 시간표 탭에 내 시간표 추가
- 내 시간표의 시간표 삭제 버튼 숨김
- 내 시간표에 과목 추가 버튼 비활성화
- 메인 페이지 타임라인 myTimetable 표시
v1.3.0+21 배포

Add my timetable in timetable page

---

.github/workflows/test.yml
CONTRIBUTING.md
android/app/build.gradle
android/gradle.properties
assets/translations/en.json
assets/translations/ko.json
ios/Runner.xcodeproj/project.pbxproj
lib/home.dart
lib/pages/main_page.dart
lib/pages/settings_page.dart
lib/pages/timetable_page.dart
pubspec.lock
pubspec.yaml

- add English locales
- fix android gradle build
- fix iOS integration test workflow (깃헙 액션 실행 후 모든 시뮬레이터를 종료하는 단계 추가)
- add documentation (번역 관련 g11n 태그 추가)

Add english locales

---

README.md
android/gradle.properties
lib/providers/timetable_model.dart

- Fix timetableindex changing to wrong index
- Fix android gradle properties

Fix timetableindex changing to wrong index

---

.github/workflows/build.yml
.github/workflows/coverage.yml
.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/test.yml
ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner/Info.plist
lib/main.dart
pubspec.lock
pubspec.yaml

- 기존에는 특별히 폰트를 지정하지 않았고, 각 시스템의 기본 폰트를 사용했던 것으로 추측됩니다.
- Noto Sans KR 폰트를 추가하고, 앱 기본 폰트로 지정하였습니다.
- flutter version을 `3.7`로 올렸습니다.
- 로컬에서는 `3.7.7` 버전으로 테스트했습니다.
- CI/CD 환경은 `3.3.6` > `3.7`으로 변경하였습니다.

feat: update to flutter 3.7 and apply NotoSans-KR

---

lib/constants/url.dart
lib/home.dart
lib/main.dart
lib/pages/liked_review_page.dart
lib/pages/my_review_page.dart
lib/pages/review_page.dart
lib/pages/user_page.dart
lib/providers/hall_of_fame_model.dart
lib/providers/liked_review_model.dart
lib/widgets/backdrop.dart

|명예의 전당|내 정보|좋아요한 후기|
|---|---|---|
|![Simulator Screenshot - iPhone 14 Pro - 2023-06-30 at 01 35 17](https://github.com/sparcs-kaist/otl-app/assets/30364442/3ab4a517-b1f4-4768-9904-98235763cc3b)|![Simulator Screenshot - iPhone 14 Pro - 2023-06-30 at 01 35 56](https://github.com/sparcs-kaist/otl-app/assets/30364442/c4154eb2-8b05-41c7-afd7-a58a9ed7a85b)|![Simulator Screenshot - iPhone 14 Pro - 2023-06-30 at 01 36 25](https://github.com/sparcs-kaist/otl-app/assets/30364442/85ed2d67-0aea-4bc8-a667-272c991bae10)|

Resolve #86, add liked reviews, hall of fame, modify my reviews, latest reviews

---

assets/translations/ko.json
lib/constants/privacy.dart
lib/providers/course_search_model.dart
lib/providers/lecture_search_model.dart
lib/widgets/review_block.dart
lib/widgets/review_write_block.dart

Feat@final

---

pubspec.yaml

Change version to 2.0.1

---

lib/constants/url.dart
lib/pages/login_page.dart
lib/widgets/pop_up.dart

- 서버 URL Host를 https://otl.kaist.ac.kr 에서 https://otl.sparcs.org 로 변경

Change server host to otl.sparcs.org

---

.github/workflows/build.yml
.github/workflows/coverage.yml
.github/workflows/release.yml
.github/workflows/test.yml
android/app/build.gradle
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
lib/providers/info_model.dart
pubspec.yaml

- Change deprecated `compileSdkVersion` to `compileSdk`
- Update to com.android.tools.build:gradle:8.1.0
- Update gradle version to 8.3

Change version to 2.0.2, update Android deps, fix Github Actions warnings

---

.github/workflows/coverage.yml
lib/constants/url.dart
lib/dio_provider.dart
lib/models/lecture.dart
lib/pages/lecture_search_page.dart
lib/pages/login_page.dart
lib/pages/review_page.dart
lib/pages/timetable_page.dart
lib/providers/lecture_search_model.dart
lib/providers/timetable_model.dart
lib/widgets/lecture_group_block_row.dart
lib/widgets/lecture_search.dart
lib/widgets/semester_picker.dart
lib/widgets/timetable_summary.dart
pubspec.lock
pubspec.yaml
test/models/lecture_test.dart
test/pages/pump_test.dart
test/utils/extensions.dart
test/utils/samples.dart
test/widgets/pump_test.dart
test/widgets/review_block_test.dart

- Bug fix: `Humanities & Social Elective(Humanit` not match with `Humanities & Social Elective` type. [Bug report](https://www.notion.so/App-T-bb51137d86584ea794e061aac0b49264)
- Add unit tests on lecture type classification method
2022년 봄학기 학사정보부터 인문선택과목(HSE)의 영문 type명이 `Humanities & Social Elective`에서 `Humanities & Social Elective(Humanities-General)`로 변경되었지만, 앱 내에서 과목을 분류할 때 exact string match를 통해 확인하기 때문에 바뀐 type명을 제대로 분류하지 못하고, 기타 과목으로 분류됨
- 기존의 exact string match가 아닌 type명의 시작 문자열 확인을 통해 과목 type을 분류하도록 수정 3a95f45ba151c7c23fb6064e69f6d97250900c5e
- 추후에도 학사정보가 업데이트될 경우 영문 type명이 변경될 가능성이 있기 때문에 최신 학사정보 데이터에 대해 classification이 제대로 되는지 확인하기 위한 unit test 추가 68cdb2e8915dac5900326a325e24b107957ab304

Fix lecture type classification bug for HSS Elective

---

android/build.gradle
pubspec.yaml

Update version to 2.0.3

---

lib/constants/color.dart
lib/pages/lecture_detail_page.dart
lib/widgets/timetable_block.dart
lib/widgets/today_timetable.dart

Deprecated 처리한 코드들 제거
- 시간표 블록에 showProfessor 변수 제거
- old color styles에 해당하는 색 제거 및 관련된 디자인 수정

Delete deprecated variables and modify the associated designs

---

lib/providers/timetable_model.dart

- 내 시간표가 이미지 내보내기가 안 되는 문제 해결
- id 값이 원인

Fix bug that cannot export image of "내 시간표" by changing myTimetable id

---

pubspec.yaml

이번 버전은 중간고사 이전인 만큼 기능 추가 없이 버그 수정 및 코드 리팩터링을 중심으로 가려고 합니다~

Change version to 2.2.1

---

README.md

Resolve #167, Edit README.md

---

lib/providers/info_model.dart

이슈 #185 번을 해결합니다. 
| 스크린샷 1 | 스크린샷 2 |
|---|---|
|![Screenshot_1724906913](https://github.com/user-attachments/assets/7262fd8b-b4ae-4016-80d4-b7a595411d60)|![Screenshot_1724906930](https://github.com/user-attachments/assets/1db76131-364f-4c3d-be74-438a5e494c33)|

Send user informations to channel talk

---

.github/workflows/build.yml
.github/workflows/test.yml
ios/Podfile.lock
pubspec.lock
pubspec.yaml
test/models/lecture_test.dart

- change app version 2.5.1
- update flutter pub dependencies
- GitHub Actions: change macOS version to 15, Xcode version to 16.2
- fix failed test

Update version to 2.5.1

---

android/app/src/main/java/org/sparcs/otlplus/api/TimetableData.kt

#212.
Placeholder 업데이트.
서버에서 current semester를 가져와야 하지만 개강이 이틀 남은 관계로 일단 이렇게 두었습니다.

Replace Placeholder

---

.gitignore
android/app/src/main/AndroidManifest.xml
ios/Runner/Info.plist
lib/constants/url.dart
lib/dio_provider.dart
lib/main.dart
lib/models/timetable.dart
lib/pages/login_page.dart
lib/pages/user_page.dart
lib/providers/auth_model.dart
lib/providers/info_model.dart
lib/services/storage_service.dart
pubspec.lock
pubspec.yaml

- CallBack 기반 로그인으로 수정합니다.
- 더이상 쿠키에 로그인을 의존하지 않습니다.

feat Auto Login & Login V2

---

devtools_options.yaml
lib/home.dart
lib/main.dart
lib/providers/course_search_model.dart
pubspec.lock

그냥 home 빌드 전에 딜레이를 넣었어요! 
근데 별로 티 안나니까 상관 없을 듯?
+) 기존에 수정 버전에서 model에도 .tr()이 걸려있어서 언어 바꿀 때 바로 변경사항 적용이 안되는 오류가 있는 거 같아서 몇개 .tr() 다 제거했습니다

fix localizaiton error
